//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wingtip.Tools.Linq2SharePoint {
	using System;
	
	
	internal partial class WingtipDataContext : Microsoft.SharePoint.Linq.DataContext {
		
		#region Extensibility Method Definitions
		partial void OnCreated();
		#endregion
		
		public WingtipDataContext(string requestUrl) : 
				base(requestUrl) {
			this.OnCreated();
		}
		
		/// <summary>
		/// List of Wingtip Contacts
		/// </summary>
		[Microsoft.SharePoint.Linq.ListAttribute(Name="WingtipContacts")]
		public Microsoft.SharePoint.Linq.EntityList<WingtipContact> WingtipContacts {
			get {
				return this.GetList<WingtipContact>("WingtipContacts");
			}
		}
		
		[Microsoft.SharePoint.Linq.ListAttribute(Name="WingtipInvoices")]
		public Microsoft.SharePoint.Linq.EntityList<WingtipInvoice> WingtipInvoices {
			get {
				return this.GetList<WingtipInvoice>("WingtipInvoices");
			}
		}
	}
	
	/// <summary>
	/// Create a new list item.
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Item", Id="0x01")]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(WingtipContact))]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(WingtipInvoice))]
	[System.Runtime.Serialization.DataContractAttribute()]
	internal partial class Item : Microsoft.SharePoint.Linq.ITrackEntityState, Microsoft.SharePoint.Linq.ITrackOriginalValues, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging {
		
		[System.Runtime.Serialization.DataMemberAttribute()]
		private System.Nullable<int> _id;
		
		[System.Runtime.Serialization.DataMemberAttribute()]
		private System.Nullable<int> _version;
		
		[System.Runtime.Serialization.DataMemberAttribute()]
		private string _path;
		
		[System.Runtime.Serialization.DataMemberAttribute()]
		private Microsoft.SharePoint.Linq.EntityState _entityState;
		
		[System.Runtime.Serialization.DataMemberAttribute()]
		private System.Collections.Generic.IDictionary<string, object> _originalValues;
		
		[System.Runtime.Serialization.DataMemberAttribute()]
		private string _title;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion

		Microsoft.SharePoint.Linq.EntityState Microsoft.SharePoint.Linq.ITrackEntityState.EntityState {
			get {
				return this._entityState;
			}
			set {
				if ((value != this._entityState)) {
					this._entityState = value;
				}
			}
		}

		System.Collections.Generic.IDictionary<string, object> Microsoft.SharePoint.Linq.ITrackOriginalValues.OriginalValues {
			get {
				if ((null == this._originalValues)) {
					this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
				}
				return this._originalValues;
			}
		}
		
		public Item() {
			this.Initialize();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ID", Storage="_id", ReadOnly=true, FieldType="Counter")]
		public System.Nullable<int> Id {
			get {
				return this._id;
			}
			set {
				if ((value != this._id)) {
					this.OnPropertyChanging("Id", this._id);
					this._id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="owshiddenversion", Storage="_version", ReadOnly=true, FieldType="Integer")]
		public System.Nullable<int> Version {
			get {
				return this._version;
			}
			set {
				if ((value != this._version)) {
					this.OnPropertyChanging("Version", this._version);
					this._version = value;
					this.OnPropertyChanged("Version");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FileDirRef", Storage="_path", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
		public string Path {
			get {
				return this._path;
			}
			set {
				if ((value != this._path)) {
					this.OnPropertyChanging("Path", this._path);
					this._path = value;
					this.OnPropertyChanged("Path");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Title", Storage="_title", Required=true, FieldType="Text")]
		public virtual string Title {
			get {
				return this._title;
			}
			set {
				if ((value != this._title)) {
					this.OnPropertyChanging("Title", this._title);
					this._title = value;
					this.OnPropertyChanged("Title");
				}
			}
		}
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void Initialize() {
			this.OnCreated();
		}
		
		[System.Runtime.Serialization.OnDeserializedAttribute()]
		private void OnDeserialized(System.Runtime.Serialization.StreamingContext context) {
			this.Initialize();
		}
		
		protected virtual void OnPropertyChanged(string propertyName) {
			if ((null != this.PropertyChanged)) {
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		protected virtual void OnPropertyChanging(string propertyName, object value) {
			if ((null == this._originalValues)) {
				this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
			}
			if ((false == this._originalValues.ContainsKey(propertyName))) {
				this._originalValues.Add(propertyName, value);
			}
			if ((null != this.PropertyChanging)) {
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
	}
	
	/// <summary>
	/// Base Wingtip Contact Type
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="WingtipContact", Id="0x0100D654C9A8BF564992A0E65F8ACB0D4B66")]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(WingtipCustomer))]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(WingtipSupplier))]
	[System.Runtime.Serialization.DataContractAttribute()]
	internal partial class WingtipContact : Item {
		
		[System.Runtime.Serialization.DataMemberAttribute()]
		private string _contactID;
		
		[System.Runtime.Serialization.DataMemberAttribute()]
		private string _companyName;
		
		[System.Runtime.Serialization.DataMemberAttribute()]
		private System.Nullable<Country> _country;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public WingtipContact() {
			this.Initialize();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WingtipContactID", Storage="_contactID", Required=true, FieldType="Text")]
		public string ContactID {
			get {
				return this._contactID;
			}
			set {
				if ((value != this._contactID)) {
					this.OnPropertyChanging("ContactID", this._contactID);
					this._contactID = value;
					this.OnPropertyChanged("ContactID");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WingtipCompanyName", Storage="_companyName", FieldType="Text")]
		public string CompanyName {
			get {
				return this._companyName;
			}
			set {
				if ((value != this._companyName)) {
					this.OnPropertyChanging("CompanyName", this._companyName);
					this._companyName = value;
					this.OnPropertyChanged("CompanyName");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WingtipCountry", Storage="_country", FieldType="Choice")]
		public System.Nullable<Country> Country {
			get {
				return this._country;
			}
			set {
				if ((value != this._country)) {
					this.OnPropertyChanging("Country", this._country);
					this._country = value;
					this.OnPropertyChanged("Country");
				}
			}
		}
		
		private void Initialize() {
			this.OnCreated();
		}
		
		[System.Runtime.Serialization.OnDeserializedAttribute()]
		private void OnDeserialized(System.Runtime.Serialization.StreamingContext context) {
			this.Initialize();
		}
	}
	
	/// <summary>
	/// Wingtip Invoices
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="WingtipInvoice", Id="0x010039D9B22CE0F64694AADB0DD53EDDEE08")]
	[System.Runtime.Serialization.DataContractAttribute()]
	internal partial class WingtipInvoice : Item {
		
		[System.Runtime.Serialization.DataMemberAttribute()]
		private string _invoiceID;
		
		[System.Runtime.Serialization.DataMemberAttribute()]
		private System.Nullable<System.DateTime> _invoiceDate;
		
		[System.Runtime.Serialization.DataMemberAttribute()]
		private System.Nullable<double> _quantity;
		
		[System.Runtime.Serialization.DataMemberAttribute()]
		private System.Nullable<double> _total;
		
		[System.Runtime.Serialization.DataMemberAttribute()]
		private string _contactID;
		
		[System.Runtime.Serialization.DataMemberAttribute()]
		private string _address;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public WingtipInvoice() {
			this.Initialize();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WingtipInvoiceID", Storage="_invoiceID", FieldType="Text")]
		public string InvoiceID {
			get {
				return this._invoiceID;
			}
			set {
				if ((value != this._invoiceID)) {
					this.OnPropertyChanging("InvoiceID", this._invoiceID);
					this._invoiceID = value;
					this.OnPropertyChanged("InvoiceID");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WingtipInvoiceDate", Storage="_invoiceDate", FieldType="DateTime")]
		public System.Nullable<System.DateTime> InvoiceDate {
			get {
				return this._invoiceDate;
			}
			set {
				if ((value != this._invoiceDate)) {
					this.OnPropertyChanging("InvoiceDate", this._invoiceDate);
					this._invoiceDate = value;
					this.OnPropertyChanged("InvoiceDate");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WingtipInvoiceQuantity", Storage="_quantity", FieldType="Number")]
		public System.Nullable<double> Quantity {
			get {
				return this._quantity;
			}
			set {
				if ((value != this._quantity)) {
					this.OnPropertyChanging("Quantity", this._quantity);
					this._quantity = value;
					this.OnPropertyChanged("Quantity");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WingtipInvoiceTotal", Storage="_total", FieldType="Number")]
		public System.Nullable<double> Total {
			get {
				return this._total;
			}
			set {
				if ((value != this._total)) {
					this.OnPropertyChanging("Total", this._total);
					this._total = value;
					this.OnPropertyChanged("Total");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WingtipContactID", Storage="_contactID", FieldType="Text")]
		public string ContactID {
			get {
				return this._contactID;
			}
			set {
				if ((value != this._contactID)) {
					this.OnPropertyChanging("ContactID", this._contactID);
					this._contactID = value;
					this.OnPropertyChanged("ContactID");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WingtipInvoiceAddress", Storage="_address", FieldType="Text")]
		public string Address {
			get {
				return this._address;
			}
			set {
				if ((value != this._address)) {
					this.OnPropertyChanging("Address", this._address);
					this._address = value;
					this.OnPropertyChanged("Address");
				}
			}
		}
		
		private void Initialize() {
			this.OnCreated();
		}
		
		[System.Runtime.Serialization.OnDeserializedAttribute()]
		private void OnDeserialized(System.Runtime.Serialization.StreamingContext context) {
			this.Initialize();
		}
	}
	
	/// <summary>
	/// Customer of Wingtip
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="WingtipCustomer", Id="0x0100D654C9A8BF564992A0E65F8ACB0D4B6600D458F4EF7D494F43B84D46C30F7BA444")]
	[System.Runtime.Serialization.DataContractAttribute()]
	internal partial class WingtipCustomer : WingtipContact {
		
		[System.Runtime.Serialization.DataMemberAttribute()]
		private System.Nullable<CustomerLevel> _customerLevel;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public WingtipCustomer() {
			this.Initialize();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WingtipCustomerLevel", Storage="_customerLevel", Required=true, FieldType="Choice")]
		public System.Nullable<CustomerLevel> CustomerLevel {
			get {
				return this._customerLevel;
			}
			set {
				if ((value != this._customerLevel)) {
					this.OnPropertyChanging("CustomerLevel", this._customerLevel);
					this._customerLevel = value;
					this.OnPropertyChanged("CustomerLevel");
				}
			}
		}
		
		private void Initialize() {
			this.OnCreated();
		}
		
		[System.Runtime.Serialization.OnDeserializedAttribute()]
		private void OnDeserialized(System.Runtime.Serialization.StreamingContext context) {
			this.Initialize();
		}
	}
	
	/// <summary>
	/// Supplier of Wingtip
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="WingtipSupplier", Id="0x0100D654C9A8BF564992A0E65F8ACB0D4B66009FBA6CDECBAC4F5D81ECC7433A3F5A83")]
	[System.Runtime.Serialization.DataContractAttribute()]
	internal partial class WingtipSupplier : WingtipContact {
		
		[System.Runtime.Serialization.DataMemberAttribute()]
		private System.Nullable<int> _supplierAccountId;
		
		[System.Runtime.Serialization.DataMemberAttribute()]
		private string _supplierAccount;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public WingtipSupplier() {
			this.Initialize();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WingtipSupplierAccount", Storage="_supplierAccountId", Required=true, FieldType="User", IsLookupId=true)]
		public System.Nullable<int> SupplierAccountId {
			get {
				return this._supplierAccountId;
			}
			set {
				if ((value != this._supplierAccountId)) {
					this.OnPropertyChanging("SupplierAccountId", this._supplierAccountId);
					this._supplierAccountId = value;
					this.OnPropertyChanged("SupplierAccountId");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WingtipSupplierAccount", Storage="_supplierAccount", ReadOnly=true, FieldType="User", IsLookupValue=true)]
		public string SupplierAccount {
			get {
				return this._supplierAccount;
			}
			set {
				if ((value != this._supplierAccount)) {
					this.OnPropertyChanging("SupplierAccount", this._supplierAccount);
					this._supplierAccount = value;
					this.OnPropertyChanged("SupplierAccount");
				}
			}
		}
		
		private void Initialize() {
			this.OnCreated();
		}
		
		[System.Runtime.Serialization.OnDeserializedAttribute()]
		private void OnDeserialized(System.Runtime.Serialization.StreamingContext context) {
			this.Initialize();
		}
	}
	
	internal enum Country : int {
		
		None = 0,
		
		Invalid = 1,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Italy")]
		Italy = 2,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="USA")]
		USA = 4,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Germany")]
		Germany = 8,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="France")]
		France = 16,
	}
	
	internal enum CustomerLevel : int {
		
		None = 0,
		
		Invalid = 1,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Level A")]
		LevelA = 2,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Level B")]
		LevelB = 4,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Level C")]
		LevelC = 8,
	}
}
